# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92db076d4b13b0af7a5de84f67d9b00c85fc2b427b9ac7dc4aa4184a988f63e28572469aa03efcc029fb47037383357d9666d6b0c1b4893543247db7c15810cf

test:
  secret_key_base: 403276d6bd34c210005ebbc110ca85325fe5d4708fa8d83d975c51ee6ebe15b5136ed2f5ebe1b6b2e17e80829ce8eb60e82686033e16351363d6632e8d51cd89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
